version: "3.8"
services:
  express:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DATABASE_HOST: $DATABASE_HOST
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_NAME:$DATABASE_NAME
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD:$DATABASE_PASSWORD
      MYSQL_DATABASE:$DATABASE_NAME
      MYSQL_USER:$DATABASE_USER
      MYSQL_PASSWORD:$DATABASE_PASSWORD
