version: "3.8"
services:
  express:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DATABASE_HOST: $DB_HOST
      DATABASE_USER: $DB_USER
      DATABASE_PASSWORD: $DB_PASSWORD
      DATABASE_NAME: $DB_NAME
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD